#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.Generic{1,0,0
#
ToF10120_LIDAR_Demo.x430: package/cfg/ToF10120_LIDAR_Demo.x430.mak

clean::
	-$(RM) package/cfg/ToF10120_LIDAR_Demo.x430.mak
